name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Lint
        run: uv run poe lint

      - name: Check formatting
        run: uv run poe format:check

      - name: Check types
        run: uv run poe typecheck

      - name: Test
        run: uv run poe test

